[accessorySettings]
clockAccessory = false
compassAccessory = false
recoveryCompassAccessory = false
calendarAccessory = false
elytraAccessory = true
spyglassAccessory = false
lanternAccessory = false
totemOfUndyingAccessory = true
enderChestAccessory = false
shulkerBoxAccessory = false
arrowAccessory = false