[accessorySettings]
clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
calendarAccessory = true
elytraAccessory = true
spyglassAccessory = true
lanternAccessory = true
totemOfUndyingAccessory = true
enderChestAccessory = true
shulkerBoxAccessory = false
arrowAccessory = true